src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?ServiceV $serviceId = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $UserId = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getServiceId(): ?ServiceV
    {
        return $this->serviceId;
    }

    public function setServiceId(?ServiceV $serviceId): self
    {
        $this->serviceId = $serviceId;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->UserId;
    }

    public function setUserId(?User $UserId): self
    {
        $this->UserId = $UserId;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{

    private $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('UserId', EntityType::class, [
                'class' => User::class,
                'choices' => $this->userRepository->findAll(),
                'choice_label' => 'email',
                'choice_value' => 'id',
                'required' => true,
                'placeholder' => 'choisir une utilisateur'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Dompdf\Dompdf;
use Dompdf\Options;

#[Route('/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_reser', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservation' =>  $reservationRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_reser_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }


    #[Route('/{id}/pdf', name: 'app_reser_pdf', methods: ['GET'])]
    public function pdf(Reservation $reservation): Response
    {

        $tableHTML = $reservation->getId() . "<br/>" . $reservation->getUserId()->getEmail() . "<br/>" . $reservation->getServiceId()->getNom() . "<br/>" . $reservation->getServiceId()->getPrix() . "<br/>" . $reservation->getDate()->format('Y-m-d H:i:s');

        $pdfOption = new Options();
        $pdfOption->set('defaultFont', 'sans-serif');

        $dompdf = new Dompdf($pdfOption);
        $dompdf->loadHtml($tableHTML);

        $dompdf->setPaper('A4', 'portrait');

        $dompdf->render();

        $pdfContent = $dompdf->output();


        return new Response($pdfContent, 200, array(
            'Content-Type' => 'application/pdf'
        ));
    }
}

templates/reservation/index.html.twig
{% extends "back/baseback.html.twig" %}

{% block title %}Service Vétérinaire{% endblock %}


{% block body %}
    <h1>Service Vétérinaire</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>USER</th>
                <th>SERVICE</th>
                <th>DATE</th>
            </tr>
        </thead>
        <tbody>
        {% for item in reservation %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.userId.email }}</td>
                <td>{{ item.serviceId.nom }}</td>
                <td>{{ item.date ? item.date|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_reser_show', {'id': item.id}) }}" class="btn btn-info active btn-sm" role="button" >Afficher</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/reservation/show.html.twig
{% extends "back/baseback.html.twig" %}

{% block title %}Service Vétérinaire{% endblock %}

{% block body %}
    <h1>Service Vétérinaire</h1>

    <a href="{{ path('app_reser_pdf', {'id': reservation.id }) }}"class="btn btn-info active btn-sm" role="button">EXPORT PDF</a>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>User</th>
                <td>{{ reservation.userId.email }}</td>
            </tr>
            <tr>
                <th>Service</th>
                <td>{{ reservation.serviceId.nom }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ reservation.date ? reservation.date|date('Y-m-d') : '' }}</td>
            </tr>
        
        </tbody>
    </table>

    <a href="{{ path('app_reser') }}"class="btn btn-info active btn-sm" role="button">page précedente</a>

{% endblock %}